name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Bump Versions
      uses: remorses/bump-version@v8
      with:
          version_file: ./VERSION
    
    - uses: actions/checkout@v1
    
    - name: Build & Push Image
      run: |
        echo "${{ secrets.DOCKERPW }}" | docker login -u "pkdoughnut" --password-stdin
        docker image build -t pkdoughnut/test:latest .
        docker push pkdoughnut/test:latest
