name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Scan image for vulnerabilities
      uses: docker://docker.io/aquasec/trivy:0.2.1
      with:
         args: --cache-dir /var/lib/trivy --exit-code 1 --no-progress docker.pkg.github.com/pkdoughnut/dev-sec-ops-seed/seed:${{ github.sha }}
    
    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.36.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
       
    - name: Build & Push Image
      run: |
        echo "${{ secrets.DOCKERPW }}" | docker login -u "pkdoughnut" --password-stdin
        docker image build -t pkdoughnut/test:latest .
        docker push pkdoughnut/test:latest
